#!/usr/bin/env sh

RED='\033[31m'
NC='\033[0m'

npx lint-staged --quiet >/dev/null 2>&1 || { printf "${RED}✗ Lint başarısız${NC}\n"; exit 1; }
npm run type-check -s >/dev/null 2>&1 || { printf "${RED}✗ TypeScript hatası${NC}\n"; exit 1; }
